apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-app
  namespace: nuxt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuxt-app
  template:
    metadata:
      labels:
        app: nuxt-app
    spec:
      containers:
      - name: nuxt-container
        image: nuxt-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nuxt-service
  namespace: nuxt
spec:
  type: NodePort
  selector:
    app: nuxt-app
  ports:
    - protocol: TCP
      port: 80       # Puerto interno del clúster
      targetPort: 3000 # Puerto del contenedor
      nodePort: 30080  # Puerto expuesto en tu máquina local