name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v3

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.actor }}/nuxt-k8s-argocd
        event-type: new-image-nuxt-app
        client-payload: >
          {
            "image": "localhost:30500/nuxt-app:${{ github.sha }}"
          }
