name: Local Image Update Live

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v3

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.actor }}/nuxt-k8s-argocd
        event-type: new-local-image-update
        client-payload: >
          {
            "image": "nuxt-app:${{ github.sha }}"
            "env": "live",
            "app": "nuxt-app"
          }
